### ISSUE TITLE
Clarification about the workflow when setting up contract with override 

### ISSUE THREAD

**Issue by clemsos** [manifoldxyz/royalty-registry-solidity#13]
Hello, I have a simple question: are the various platforms (the ones in `contracts/specs` folder) currently querying the royal registry to parse their royalties ? 

I am planning to add the override directly to my ERC721 contract by following the [example](https://github.com/manifoldxyz/royalty-registry-solidity/blob/main/contracts/token/ERC721.sol), so from what I gather I don't need to call `setRoyaltyLookupAddress` on the registry.

I am just unclear how the various platforms request the registry to fetch the royalty.

Many thanks for the very useful project!

**Comment by wwhchung** [comment]
If you have a new contract the recommendation is to just integrate eip2981 right into your contract (the repo has a reference implementation you can use). 

The marketplaces have committed to referencing the registry for backwards compatible overrides. The status of that, you’d have to check in with them.

**Comment by clemsos** [comment]
Thank you very much for your answer. 

Just to be sure, the `EIP2981RoyaltyOverrideCore ` in this [ERC721 exmaple](https://github.com/manifoldxyz/royalty-registry-solidity/blob/main/contracts/token/ERC721.sol) is the reference implementation you mentioned ?
