### ISSUE TITLE
Royalty Engine Compatibility with OZ upgradeable contracts?

### ISSUE THREAD

**Issue by waynehoover** [manifoldxyz/royalty-registry-solidity#23]
Hello, 

I have a contract:

```
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721URIStorageUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/interfaces/IERC2981Upgradeable.sol";
...

contract MyContract is
    OwnableUpgradeable,
    ERC721URIStorageUpgradeable,
    IERC2981Upgradeable
...
```

and have defined
```    
function royaltyInfo(uint256 tokenId, uint256 salePrice)
        external
        view
        override
        returns (address receiver, uint256 royaltyAmount)
```
and 
```function supportsInterface(bytes4 interfaceId)```

On the contract but getRoyaltyView on the royalty registry does not work. When I use the implementation address (not the proxy address) it works, but as expected gives an empty array back (there is no data stored on the implementation address in the proxy pattern).

Is the royalty registry not compatible with upgradable contracts or did I do something wrong in implementing ERC2981?

**Comment by wwhchung** [comment]
It does work.  There's probably an issue with your implementation.  The sample you provided above doesn't appear to show the return value.  If that's incorrect, it won't work.  There are quite a few examples out there that use proxy and work as expected.  Where's your contract location?

**Comment by wwhchung** [comment]
Your signature should look like this:
https://github.com/manifoldxyz/royalty-registry-solidity/blob/main/contracts/specs/IEIP2981.sol

**Comment by waynehoover** [comment]
Thanks, I believe I am returning the correct values (address, uint256). 

When the I put in the contract address into the lookup UI `0x1Ba47028829b68B12086287a145E87B4DC6B8726` (on mumbai): https://royaltyregistry.xyz/lookup I get an error `Error: Address not recognized.` But when I go to register the same address I get `This Token already supports EIP2981 and you DO NOT need to set a new override.`

Does the engine only lookup addresses that have been written as an override in the registry?

**Comment by waynehoover** [comment]
Maybe I need to call https://github.com/manifoldxyz/royalty-registry-solidity/blob/main/contracts/RoyaltyEngineV1.sol#L64 on the address? Because it has been upgraded, so maybe it's cached. But I don't see that function in the write contract area on polygon scan mumbai.

**Comment by wwhchung** [comment]
No, that upgrade is not live yet.

Can you verify your implementation contract so I can take a look at what's going on?

**Comment by wwhchung** [comment]
Looking at the console when we try to make the call, I'm seeing:
code: 3
data: "0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016496e76616c696420726f79616c747920616d6f756e7400000000000000000000"
message: "execution reverted: Invalid royalty amount"

What are you passing back?

**Comment by waynehoover** [comment]
You can see what it passes back by calling `royaltyInfo` on the contract 0x0CC9F41a5bDc884A95dEfB0b38DED565BB36C7BF

for (1,1) it passes back:`0x6C4FD6C088Dd8Fc8Fb0a70a98FaF709C39bed5bc, 0` is the issue that the amount is `0`?

**Comment by wwhchung** [comment]
It's likely hitting the gas limit.  That change is still on mumbai but we rolled it back on the other networks because the limit was too low.  Let me roll it back on mumbai.

The changeset was related to this:
https://github.com/manifoldxyz/royalty-registry-solidity/issues/17

**Comment by waynehoover** [comment]
That would make sense because proxy contracts are more gas expensive to call (which explains why when I used the implementation address it worked).

**Comment by wwhchung** [comment]
hmm, looks like that wasn't it, seems like something in the contract is reverting.  Let me know when it's verified and I can take a closer look.

**Comment by waynehoover** [comment]
Okay, well, here is the contract and abi: https://gist.github.com/waynehoover/d08c7e1f91652e82caecb00eaa15fa0b

Having trouble with polygonscan at the moment, does that work?

**Comment by wwhchung** [comment]
Was going to use polygonscan to dig into the code itself and find out where it's breaking.  Can't do much before that unforunately.  I rolled back, but it's still reverting.  Let me know when it's up.

**Comment by waynehoover** [comment]
Okay, I have verified the contract: https://mumbai.polygonscan.com/address/0x1Ba47028829b68B12086287a145E87B4DC6B8726#writeProxyContract

**Comment by wwhchung** [comment]
Looks functional to me now!

**Comment by waynehoover** [comment]
Amazing, me too. Was it that I needed to verify the contract?

**Comment by wwhchung** [comment]
No, I have no idea what happened, lol.  We don't do any contract signature verification.  Could have been that something was up with the polygonscan node and the updated no-gas limit implementation didn't sync yet.  Pretty sure it was the gas limit issue.  It's been bumped up, but for now I've just rolled back to a no-gas limit implementation, just like on ethereum mainnet.

**Comment by waynehoover** [comment]
Thanks again. 👋 I'm going to close the ticket, as this is solved for me now. Glad we could figure it out.
