### ISSUE TITLE
Wallet owns B, which owns A – how to set royalties on A?

### ISSUE THREAD

**Issue by osetinsky** [manifoldxyz/royalty-registry-solidity#24]
We're facing an issue setting on-chain royalties for a [collection](https://opensea.io/collection/1989-sisters?search[sortAscending]=false&search[sortBy]=LAST_SALE_PRICE) we launched on OpenSea.

While following OpenSea example contracts for a primary crowd sale through their marketplace, I overlooked some missing ownership transfer logic. The logic would allow for the deployment wallet to transferOwnership of the main collection contract A _back_ to itself from the factory crowd sale contract B owned by the wallet. Upon deployment, we had our wallet [grant ownership](https://github.com/ProjectOpenSea/opensea-creatures/blob/master/migrations/2_deploy_contracts.js#L41) of contract A to contract B in order for contract B to mint tokens, but we now have no way of using our deployment wallet to retake ownership of contract A from contract B. I know that's a lot to follow.

This is a problem because without our wallet being owner() of contract A, we're unable to use that wallet to set royalties for the contract A that holds our collection and has started trading through on-chain-only platforms.

This was our first foray into NFTs, so I guess you live and you learn, but it's still hard to believe there's no way for me to prove that, as owner of B, I own A because A is owned by B. Maybe I'm missing something fundamental.

OpenSea is actually [updating](https://github.com/ProjectOpenSea/opensea-creatures/compare/update-2204) their templates to address this issue, so I doubt we're the first ones to encounter it. But is there any way for us to regain control of contract A or at least set royalties on it through the contract B our wallet owns?

**Comment by wwhchung** [comment]
I get what you’re saying. Does contract B have an ownership test? A possible solution if it does, is a check where, if the owner of a contract comes back as a contract itself,  it could check THAT contracts owner function and see if it matches the message sender. That would require a change to the registry itself and approval from the participating parties. 

If that sounds like a possible solution, you’re also free to submit a code change request with a “pass through ownership lookup”. Haven’t thought through all the implications of that though, nor the security loopholes.

**Comment by osetinsky** [comment]
@wwhchung really appreciate the quick response and glad you follow. Contract B have an ownership test (if you mean calling `owner()` returns a wallet address). Contract B returns our wallet address for owner().

I'll be looking into opening a PR for this, but a couple questions:
* any suggestions for contracts in this repo to look at as a starting point?
* what are some initial security red flags you can think of? delegatecalls come to mind

**Comment by wwhchung** [comment]
Will think more about security concerns. 

But basically it sounds like the proposal is a change to RoyaltyRegistry.sol overrideAllowed function to add a check where:

If owner of contract A is not the sender and it is a contract address, then get that contract’s (contract B) owner and allow if THAT owner matches the message sender.

**Comment by osetinsky** [comment]
@wwhchung I'll be giving this a closer look this weekend, but at first glance I'm imagining something like the below to replace the [OwnableUpgradable](https://github.com/manifoldxyz/royalty-registry-solidity/blob/main/contracts/RoyaltyRegistry.sol#L70&L72) try/catch block in `RoyaltyRegistry.overrideAllowed`:

```
        try OwnableUpgradeable(tokenAddress).owner() returns (address owner) {
            if (owner == _msgSender()) return true;

            if (owner.isContract()) {
              try OwnableUpgradeable(owner).owner() returns (address passThroughOwner) {
                  if (passThroughOwner == _msgSender()) return true;
              } catch {}
            }
        } catch {}
```

**Comment by osetinsky** [comment]
@wwhchung I just opened PR that addresses it here: https://github.com/manifoldxyz/royalty-registry-solidity/pull/25 

Curious to hear your thoughts on it. Thanks again for your input on the issue.
