### ISSUE TITLE
IManifold getRoyalties implemented but RoyaltyRegistry.xyz returns no royalty info

### ISSUE THREAD

**Issue by lucianobargmann** [manifoldxyz/royalty-registry-solidity#30]
I deployed the contract in Polygon main net, and I was able to complete the configure . 
**BUT its not working.**

Contract address is 0x59FE926a6A2bA5E503CE8fB63906491a4a937349
This is the CONFIGURE output:
```
Sending...
Sent.
Transaction Hash: 0xbb3c9d00ea441909cfea5f92cbdc14856b2eebea86cf457778044fb670bb16be
Etherscan: https://polygonscan.com/tx/0xbb3c9d00ea441909cfea5f92cbdc14856b2eebea86cf457778044fb670bb16be
Confirming...
Confirmed.
Contract Address: 0x3450557A3De25526339206E6f525DFC789eDcE45
Etherscan: https://polygonscan.com/address/0x3450557A3De25526339206E6f525DFC789eDcE45
Setting as Override Contract for 0x59FE926a6A2bA5E503CE8fB63906491a4a937349...
Transaction Hash: 0xe85b9081b873129f6c79df891536189a73b4a01f743549f2ff0b3e7ec0f23686
Etherscan: https://polygonscan.com/tx/0xe85b9081b873129f6c79df891536189a73b4a01f743549f2ff0b3e7ec0f23686
Setting...
Set.

```

I can get the Royalties using Remix:
```
getRoyalties
tokenId:
"1"
call
0:
address[]: 0xE3bB7C0D8a3BcbCB10A8B4DC79f3b94e1bDd9204,0x11F85eD2EC3b776Ef8c0b69647a2eCF08e0f7cd0
1:
uint256[]: 300,700
```

But I don't get the expected output from https://royaltyregistry.xyz/0x59FE926a6A2bA5E503CE8fB63906491a4a937349/1

Token Details
ADDRESS
0x59FE926a6A2bA5E503CE8fB63906491a4a937349
ROYALTY SPEC
EIP2981
ID
1
ETHERSCAN
https://polygonscan.com/token/0x59FE926a6A2bA5E503CE8fB63906491a4a937349?a=1
Royalties
| PAYABLE ADDRESS	| SHARE (%)	| VALUE (ETH) |
|---|---|---|
| 0x0000000000000000000000000000000000000000	| 0	| 0.0 |

I have implemented getRoyalties from IManifold as you can see in the contract code below. 

**I was expecting Royalties to be**:

| PAYABLE ADDRESS	| SHARE (%)	| VALUE (ETH) |
|---|---|---|
| 0x59FE926a6A2bA5E503CE8fB63906491a4a937349	| 3	| 0.03 |
| 0x11f85ed2ec3b776ef8c0b69647a2ecf08e0f7cd0 | 7	| 0.07 |

Where 0x59FE926a6A2bA5E503CE8fB63906491a4a937349 is the contract address, should receive 3% of the sales
And 0x11f85ed2ec3b776ef8c0b69647a2ecf08e0f7cd0 is the minter of the NFT, should receive 7% of sales

What am I doing wrong in my contract that royaltyregistry.xyz is not displaying the expected royalties?
Thanks in advance, any help is much appreciated.

This is the contract CODE:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.15;


import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/security/Pausable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";

import "@manifoldxyz/royalty-registry-solidity/contracts/specs/IManifold.sol";

contract Lubar is ERC721URIStorage, Pausable, Ownable, IManifold  {

    mapping(uint256 => address payable[]) internal _receivers;
    mapping(uint256 => uint256[]) internal _bps;

    constructor() ERC721("Luke HK Collection", "LUBAR") {}

    event TokenMinted(address minter, uint256 id, address payable[] royaltyReceivers, uint256[] bps);

    function mintCar(
        uint256 tokenId,
        string memory tokenURI,
        address minterAddress)
    public onlyOwner whenNotPaused
    returns (address payable[] memory, uint256[] memory) {
        _mint(minterAddress, tokenId);
        _setTokenURI(tokenId, tokenURI);

        address payable[] memory receivers = new address payable[](2);
        receivers[0] = payable(msg.sender);
        receivers[1] = payable(minterAddress);
        _receivers[tokenId] = receivers;

        uint256[] memory bps = new uint256[](2);
        bps[0] = 300; // 3% house
        bps[1] = 700; // 7% minter
        _bps[tokenId] = bps;

        emit TokenMinted(minterAddress, tokenId, _receivers[tokenId], _bps[tokenId]);
        return (_receivers[tokenId], _bps[tokenId]);
    }

    function burn(uint256 tokenId) public onlyOwner {
        _burn(tokenId);
    }

    // IManifold -------------------
    function getRoyalties(uint256 tokenId)
    public override view
    returns (address payable[] memory, uint256[] memory) {
        return (_receivers[tokenId], _bps[tokenId]);
    }
    // END IManifold -------------------

    // Pausable -------------------
    function pause() public onlyOwner {
        _pause();
    }

    function unpause() public onlyOwner {
        _unpause();
    }

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal override whenNotPaused {
        super._beforeTokenTransfer(from, to, amount);
    }

    // END Pausable -------------------
}
```

**Comment by wwhchung** [comment]
This is because you did NOT need to set an override if your contract already supported on-chain royalties.  To view royalties, go here:
https://polygonscan.com/address/0xe7c9Cb6D966f76f3B5142167088927Bf34966a1f#writeProxyContract

And call:
setRoyaltyLookupAddress with the values:
tokenAddress: 0x59FE926a6A2bA5E503CE8fB63906491a4a937349
royaltyLookupAddress: 0x0000000000000000000000000000000000000000

This will remove the override you deployed (which, again, is not necessary).

The reason the royalty configurator did not warn you about this is because you did not implement 'supportsInterface', which is how most frontends (and some smart contracts) check for support.

**Comment by lucianobargmann** [comment]
Amazing. Thanks for the quick reply. I will add the supportsInterface implem.

**Comment by zmitzie** [comment]
@wwhchung  On a similar note, I'm as well trying to deploy an NFT contract that implements the IManfiold interface for the royalty information. I'm not setting an override in RoyaltyRegistry, but again via royaltyregistry.xyz I get an error "Address not recognized", while with Remix I'm able to get the royalty information for the given token Id. I also implement supportInterface() for IManifold.sol but still via royaltyregistry.xyz when I lookup the royalties for my NFT, I get the "Address not recognized" error. 

Any help would be highly appreciated. Thank you!

Here is a light contract I'm using:

```
pragma solidity ^0.8.2;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/introspection/ERC165.sol";
import "./interfaces/IManifold.sol";

contract NFTTest is ERC165, ERC721 {
    mapping (uint256 => address payable[]) internal _tokenRoyaltyReceivers;
    mapping (uint256 => uint256[]) internal _tokenRoyaltyBPS;

    constructor(
        string memory nftName,
        string memory nftSymbol
    ) ERC721(nftName, nftSymbol) {}

    function supportsInterface(bytes4 interfaceId) public view virtual override(ERC165, ERC721) returns (bool) {
        return interfaceId == type(IManifold).interfaceId || super.supportsInterface(interfaceId);
    }

    function mint(address to, uint256 tokenId) external {
        super._mint(to, tokenId);
    }

    function _setRoyalties(uint256 tokenId, address payable[] calldata receivers, uint256[] calldata basisPoints) public {
        _tokenRoyaltyReceivers[tokenId] = receivers;
        _tokenRoyaltyBPS[tokenId] = basisPoints;
    }

    function _getRoyaltyReceivers(uint256 tokenId) view internal returns (address payable[] storage) {
        return _tokenRoyaltyReceivers[tokenId];
    }

    function _getRoyaltyBPS(uint256 tokenId) view internal returns (uint256[] storage) {
        return _tokenRoyaltyBPS[tokenId];  
    }

    function getRoyalties(uint256 tokenId) external view returns (address payable[] memory, uint256[] memory) {
        return(_getRoyaltyReceivers(tokenId), _getRoyaltyBPS(tokenId));
    } 
}
```
