### ISSUE TITLE
`IManifold.getRoyalties` on nonexistent token

### ISSUE THREAD

**Issue by wchargin** [manifoldxyz/royalty-registry-solidity#31]
`IManifold.getRoyalties` on nonexistent token

The [docs for `getRoyalties(uint256)`][1] don't specify the intended
behavior of the API in the case where there is no token by the given ID.
In particular, if royalties are the same across all tokens for a
contract, does the contract need to look up whether the token exists and
revert otherwise, or is it sufficient to return the same list of
royalties even if there is no such token?

In particular, are there reasonable reasons that real implementations
might depend on `getRoyalties` reverting here? If not, and we can afford
to return results even for nonexistent tokens, that saves some gas on an
otherwise unnecessary check.

For a simple motivating example, consider:

```solidity
contract MyToken is ERC721, Ownable {
    function mint() external onlyOwner { /* ... */ }

    /// Returns a 1% royalty to the owner on all tokens.
    /// Doesn't revert even if the token doesn't exist; is this okay?
    function getRoyalties(uint256 tokenId)
        external
        view
        returns (address payable[] memory, uint256[] memory)
    {
        address payable[] memory recipients = new address payable[](1);
        uint256[] memory bps = new uint256[](1);
        recipients[0] = owner();
        bps[0] = 100;
        return (recipients, bps);
    }
}
```

[1]: https://github.com/manifoldxyz/royalty-registry-solidity/blob/fee5379264bc56e0ad93d0147bbd54086b37b864/contracts/specs/IManifold.sol#L12-L19

**Comment by wwhchung** [comment]
Sorry for the delay.  If the token doesn't exist, you can return anything you wish or revert.  The marketplace would never call this function for a non-existent token, so it doesn't really matter.  If you have uniform royalties on a contract for all tokens, you could simply always return the static value.
