### ISSUE TITLE
Should we use multiple recipients or single recipient + payment splitter?

### ISSUE THREAD

**Issue by jdmwood** [manifoldxyz/royalty-registry-solidity#36]
Hi,

The royalty registry seems to natively support multiple royalty recipients (like how Rarible, Foundation etc chose to do this).

But I noticed that the latest example in [MultiReceiverRoyaltyOverrideCore.sol](https://github.com/manifoldxyz/royalty-registry-solidity/blob/main/contracts/overrides/MultiReceiverRoyaltyOverrideCore.sol) seems to use EIP-2981 and then use a payment splitter to handle receiving to a single address.

I realise this code is probably WIP, but I'm just curious about why it's done this way and not simply returning the multiple recipients to the registry?

Is there still some concern that some marketplaces can only handle single recipient royalties?

What should new contracts be doing? 2981 was pretty popular, but clearly marketplaces using the registry must have to handle multiple recipients. And, having the marketplaces distribute multiple royalties is greatly preferable to a payment splitter contract. Should we be using the native multiple response or being defensive and using an 2981 single recipient + splitter?

Thanks!

**Comment by jdmwood** [comment]
Thanks that's really helpful.

Do you know what the major marketplaces are doing if they see > 1 item returned from the registry? Do they handle that or will they just fail?

I guess I'm just curious that clearly the registry is designed to return multiple, which I'd assume would force the marketplaces who support the registry to have to handle that case. Or, was that more of a forwards compatibility thing?

e.g. for now, make sure you just return max 1 recipient, but maybe in the future it will be safe to return multiple?

**Comment by wwhchung** [comment]
Most marketplaces that are part of the list on royaltyregistry.xyz will conform and distribute to multiple recipients. OpenSea just started ingesting this data as well.

**Comment by jdmwood** [comment]
Thanks so much! I think this answers my question!
