### ISSUE TITLE
Royalty Engine On Sepolia

### ISSUE THREAD

**Issue by hironate** [manifoldxyz/royalty-registry-solidity#42]
As we all know, Goerli Gas fees are super high and it's almost unusable sometimes, so we are moving our testnet development from goerli to Sepolia. It would be great if we have Royalty look up contract deployed on depolia.

**Comment by wwhchung** [comment]
Haven't got a chance yet, but if it's for test, there's nothing stopping you from just deploying the contracts yourself in the meantime.

Alternative is to play with the mumbai deployment, since it's all the same anyways.

**Comment by quantix-nft** [comment]
Hello is there any update on this issue?
OpenSea is moving from Goerli to Sepolia. Having a self-deployed contract is not supposed to be useful because any platform like OS wouldn't use it and it wouldn't make any sense

**Comment by wwhchung** [comment]
We will support Sepolia after there is gnosis support, as it's how we manage the registry.

**Comment by mpeyfuss** [comment]
Sepolia is now supported by Safe so just wanted to bump this 🙏

**Comment by tina1998612** [comment]
+1 waiting for this

**Comment by wwhchung** [comment]
We've released on sepolia
