### ISSUE TITLE
Publish files to npm registry

### ISSUE THREAD

**Issue by shunkakinoki** [manifoldxyz/royalty-registry-solidity#8]
Could you make the files available for extensibilty to use from npm install?

**Comment by wwhchung** [comment]
They're already published:
https://www.npmjs.com/package/@manifoldxyz/royalty-registry-solidity

When you install they go into node modules and you can import like so:

import "@manifoldxyz/royalty-registry-solidity/contracts/....."

**Comment by wwhchung** [comment]
Ah, I get what you're saying.  Including the built json files in the build directory.  Will do this and publish.  Thanks for bringing it up.

**Comment by wwhchung** [comment]
Done
